adminuser:
    name: Admin felhasználók
    singular_name: Admin felhasználó
    show_menu: false
    syncable: false
    fields:
        username:
            type: text
            label: Felhasználónév
            validators:
                -
                    regexp: empty
                    message: Felhasználónév nem lehet üres!
                -
                    regexp: '/[a-z]/'
                    message: A felhasználónév névnek karaktert is tartalmaznia kell
        slug:
            type: slug
            uses: username
            visible: false
        display_name:
            type: text
            label: Megjelenítendő név
        avatar:
            type: image
        salt:
            type: random
            visible: false
        password:
            type: password
            label: Jelszó
            uses: salt
            validators:
                regexp: empty
                message: Jelszó nem lehet üres!
        permissions:
            type: permission
            label: Jogosultsági kör