host: http://rusty.bonzoportal.hu
subfolder: 
site_title: "Blocky"

site:
    title: "Blocky"
    description: "..."
    keywords: "..."

theme: default

mail:
    transportation:
        smtp: '127.0.0.1'
        port: 25
        username: 
        password:
    sender:
        email: 'info@host.hu'
        name: 'Info'
    layout: '@theme/mail/_layout.twig'

default_locale: en_GB
fallback_locale: en_US

pager:
    page_attribute: oldal
    limit_attribute: limit
    limit: 10

view:
    pager: '@theme/_pager.twig'
    layout: '@theme/_layout.twig'
    record_view: '@theme/record.twig'
    record_list: '@theme/list.twig'

default_content_manger: 'Blocky\Backend\Content\BaseContentManager'

extensions:
    - 'Blocky\Fields\FieldsExtension'
    - 'Blocky\Seo\SeoExtension'
    - 'Blocky\Forms\FormsExtension'
    - 'Blocky\Setup\SetupExtension'
    - 'Blocky\Frontend\FrontendExtension'
    - 'Blocky\Backend\BackendExtension'
    - 'Blocky\Ecommerce\EcommerceExtension'