---
host: http://rusty.bonzoportal.hu
subfolder: ~
site_title: Blocky
environment: dev
database: 'sqlite: ../../tmp/dbfile.db'
site:
  title: Blocky
  description: '...'
  keywords: '...'
  author: Blocky
  og_image: '#'
assets:
  minify: true
theme: default
mail:
  transportation:
    smtp: 127.0.0.1
    port: 25
    username: ~
    password: ~
  sender:
    email: info@host.hu
    name: Info
  layout: '@theme/mail/_layout.twig'
default_locale: hu_HU
fallback_locale: hu_HU
pager:
  page_attribute: oldal
  contenttype_attribute: tartalom
  limit_attribute: limit
  limit: 10
view:
  pager: '@theme/_pager.twig'
  layout: '@theme/_layout.twig'
  record_view: '@theme/record.twig'
  record_list: '@theme/list.twig'
default_content_manger: Blocky\Backend\Content\BaseContentManager
extensions:
- Blocky\Fields\FieldsExtension
- Blocky\Seo\SeoExtension
- Blocky\Forms\FormsExtension
- Blocky\Backend\BackendExtension
- Blocky\Logger\LoggerExtension
- Blocky\Setup\SetupExtension
- Blocky\Members\MembersExtension
- Blocky\Feed\FeedExtension
- PixelVision\ECommerce\ECommerceExtension
- Blocky\Frontend\FrontendExtension
...
