test:
    name: Tests
    singular_name: Test
    fields:
        title:
            label: Title
            type: text
            group: "Adatok"
        slug:
            label: Slug
            placeholder: Mentés során autómatikusan kitöltődik..
            uses: title
            type: slug
        email:
            group: "Más adatok"
            type: text
        asd:
            type: text
        ize:
            type: text
            label: Izé
            placeholder: Izé placeholder
            help: valami szövegmutyi
newsitem:
    name: Hírek
    singular_name: Hír
    localizable: true
    fields:
        title:
            label: Title
            type: text
            validators:
                regexp: empty
                message: A title nem lehet üres!
        slug:
            label: Slug
            placeholder: Mentés során autómatikusan kitöltődik..
            uses: title
            type: slug
        cover:
            label: cover
            type: image
        text:
            type: html
            label: Teaser
        properties:
            type: grid
            label: Props
            columns: 'Név, Érték, Kondíció'
        meta:
            type: meta
            group: Meta
product:
    name: Termékek
    singular_name: Termék
    fields:
        title:
            label: Megnevezés
            type: text
        slug:
            label: Elérési út
            placeholder: Mentés során autómatikusan kitöltődik..
            uses: title
            type: slug
        newitems:
            label: select news
            type: select
            multiple: true
            foreign: newsitem
        attributes:
            label: Attributumok
            singular_name: Attributum
            type: repeater
            group: "Attributumok"
            fields:
                name:
                    type: text
                value:
                    type: text
                icon:
                    label: Icon
                    type: image
        images:
            label: Képek
            singular_name: Kép
            type: repeater
            group: "Képek"
            fields:
                image:
                    label: image
                    type: image
pilot:
    name: Pilóták
    singular_name: Pilota
    fields:
        name:
            type: text
            label: Név
            group: "Adatok"
        slug:
            type: slug
            uses: name
        image:
            type: image
        brief:
            label: Élete
            type: html
        career:
            label: Karrier
            type: html
        informations:
            type: grid
            label: Infirmációk
            columns: "Név, Érték"
        results:
            label: Eredmények
            singular_name: "eredmény"
            type: repeater
            group: Eredmények
            fields:
                name:
                    type: text
                table:
                    type: grid
                    label: Tabella
                    columns: "Year, Entrant, Car, 1, 2, WDC, Points"
inception:
    name: Inceptions
    singular_name: Inception
    fields:
        title:
            label: Megnevezés
            type: text
        slug:
            label: Elérési út
            placeholder: Mentés során autómatikusan kitöltődik..
            uses: title
            type: slug
        attributes:
            label: Attributumok
            singular_name: Attributum
            type: repeater
            asd: true
            fields:
                name:
                    type: text
                value:
                    type: text
                images:
                    label: Képek
                    singular_name: Képe
                    type: repeater
                    asd: false
                    fields:
                        icon:
                            type: image
extrainception:
    name: Extra Inceptions
    singular_name: Extra Inception
    fields:
        title:
            label: Megnevezés
            type: text
        slug:
            label: Elérési út
            placeholder: Mentés során autómatikusan kitöltődik..
            uses: title
            type: slug
        attributes:
            label: Attributumok
            singular_name: Attributum
            type: repeater
            asd: true
            fields:
                name:
                    type: text
                value:
                    type: text
                images:
                    label: Képek
                    singular_name: Képe
                    type: repeater
                    asd: false
                    fields:
                        icon:
                            type: image
                        attributes:
                            label: Attributumok
                            singular_name: Attributum
                            type: repeater
                            asd: true
                            fields:
                                name:
                                    type: text
                                value:
                                    type: text
                                images:
                                    label: Képek
                                    singular_name: Képe
                                    type: repeater
                                    asd: false
                                    fields:
                                        icon:
                                            type: image