contactus:
  store: true
  contenttype: newsitem
  fields:
  - title
  - text
  email:
    to: andrewxxtheone@gmail.com
    subject: Kontakt form
    template: '@forms/email.twig'
  success_redirect: __none__
  success_message: 'Üzenetedet megkaptuk, nem sokára felkeresünk'