members_login:
    contenttype: member
    fields:
        - email
        - password
    manager: '\Blocky\Members\Form\LoginFormManager'
members_signup:
    contenttype: member
    store: true
    manager: '\Blocky\Members\Form\SignupFormManager'
    success_message: 'Sikeres regisztráció!'
    success_redirect: '/members/login'
members_lostpassword:
    contenttype: member
    fields:
        - email
    manager: '\Blocky\Members\Form\LostPasswordFormManager'
members_update:
    contenttype: member
    store: true
    fields:
        - password
    manager: '\Blocky\Members\Form\UpdateFormManager'
    success_message: 'Sikeres adat módosítás'
    success_redirect: '__self__'