transactions:
    show_menu: false
    syncable: false
    name: Fizetések
    singular_name: Fizetés
    fields:
        transid:
            type: random
            length: 10
            visible: false
        slug:
            type: slug
            uses: transid
        provider:
            type: text
            label: Fizetési típus
        refnumber:
            type: text
            label: Külső azonosító
        status:
            type: select
            options:
                - Függőben
                - Sikeres
                - Sikertelen
                - Lemondva
            label: Állapot
        data:
            type: text
            label: Adatok