payment_back:
  path: "/payment/back/{transaction}"
  handler:
    _controller: PixelVision\Payment\Controller\PaymentController
    _action: back
payment_ipn:
  path: "/payment/ipn/{provider}"
  handler:
    _controller: PixelVision\Payment\Controller\PaymentController
    _action: ipn
payment_start:
  path: "/payment/start/{transaction}"
  handler:
    _controller: PixelVision\Payment\Controller\PaymentController
    _action: start
payment_cancel:
  path: "/payment/cancel/{transaction}"
  handler:
    _controller: PixelVision\Payment\Controller\PaymentController
    _action: cancel