comcart:
    name: Kosarak
    singular_name: Kosár
    show_menu: false
    fields:
        email:
            type: text
        slug:
            type: slug
            uses: email
        data:
            type: text
comcategory:
  name: Kategóriák
  singular_name: Kategória
  manager: '\PixelVision\ECommerce\Content\CategoryManager'
  fields:
    title:
      type: text
    fqn:
      type: text
      visible: false
    slug:
      type: slug
      uses: fqn
      visible: false
    parent:
      type: select
      foreign: comcategory
      valueKey: fqn
comproduct:
  name: Termékek
  singular_name: Termék
  manager: '\PixelVision\ECommerce\Content\ProductManager'
  fields:
    title:
      type: text
    slug:
        type: slug
        uses: title
    price:
        type: text
    discount_price:
        type: text
    short_description:
        type: html
    long_description:
        type: html
    coverimage:
        type: image
    images:
        label: Képek
        type: repeater
        fields:
            image:
                type: image
    categories:
        type: select
        foreign: comcategory
        valueKey: fqn
        multiple: true
comorder:
    name: Rendelések
    singular_name: Rendelés
    fields:
        hash:
            type: text
        slug:
            type: slug
            uses: hash
        customer_info:
            type: json
        order_info:
            type: json
        customer:
            type: select
            foreign: member
            ajax: true