assets:
    css:
        - '@theme/assets/css/bootstrap.css'
        - '@theme/assets/css/1-col-portfolio.css'
        - '@theme/assets/css/test.scss'
    js:
        - '@theme/assets/js/jquery.js'
        - '@theme/assets/js/bootstrap.js'
        - '1000|@theme/assets/js/customForms.js'